development:
  secret_key_base: 182495289c3cd8cdb7e249d5d36058cdb1a06cf56591016ce49744207b4218ec45d435a09ce720120268aba16b50b1f1deae7b59a64ff866a27c373be0a90da2

  sports_data_api:
    :key: 'zvp866rgngxq9aua53aesaed'
    :access_level: 't'
    :mode: 'development'

test:
  secret_key_base: 7d71dbfb757e9c62dfdd2fa1d01dd089ee918072a501a874bcea7efd2b26b1c390d9da83e816b5463a69614f89fc412b208bc790db005fd75c84cf785355c50b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  sports_data_api:
  :key: 'zvp866rgngxq9aua53aesaed'
  :access_level: 't'
  :mode: 'production'
